// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trwn.Inspection.Data;

#nullable disable

namespace Trwn.Inspection.Data.Migrations
{
    [DbContext(typeof(InspectionDbContext))]
    [Migration("20260228141949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Trwn.Inspection.Models.InspectionOrderArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionReportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LotNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipmentQuantityCartons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipmentQuantityPcs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitsFinishedNotPacked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitsNotFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitsPacked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionReportId");

                    b.ToTable("InspectionOrderArticles");
                });

            modelBuilder.Entity("Trwn.Inspection.Models.InspectionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryRepresentative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionCartonNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InspectionResult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InspectionSampling")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionStandard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityMark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportNo")
                        .IsUnique();

                    b.ToTable("InspectionReports");
                });

            modelBuilder.Entity("Trwn.Inspection.Models.PhotoDocumentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionReportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionReportId");

                    b.ToTable("PhotoDocumentations");
                });

            modelBuilder.Entity("Trwn.Inspection.Models.InspectionOrderArticle", b =>
                {
                    b.HasOne("Trwn.Inspection.Models.InspectionReport", null)
                        .WithMany("InspectionOrder")
                        .HasForeignKey("InspectionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trwn.Inspection.Models.PhotoDocumentation", b =>
                {
                    b.HasOne("Trwn.Inspection.Models.InspectionReport", null)
                        .WithMany("PhotoDocumentation")
                        .HasForeignKey("InspectionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trwn.Inspection.Models.InspectionReport", b =>
                {
                    b.Navigation("InspectionOrder");

                    b.Navigation("PhotoDocumentation");
                });
#pragma warning restore 612, 618
        }
    }
}
